## Addition
def addition(a,b,c):
    return a+b+c
    print (a+b+c)
def multiplication(a,b):
    return a*b
def Division(a,b):
    return a/b
def substraction1(a,b):
    return a-b
def power1(a,b):
    return a**b